Modified to use the central library

diff --git a/cli/caliente/scripts/extract_ids b/cli/caliente/scripts/extract_ids
--- a/cli/caliente/scripts/extract_ids
+++ b/cli/caliente/scripts/extract_ids
@@ -3,26 +3,12 @@ SCRIPT="$(readlink -f "${0}")"
 BASEDIR="$(dirname "${0}")"
 SCRIPT="$(basename "${0}")"
 
-say() {
-	echo -e "${@}"
-}
+if ! . "${BASEDIR}/caliente.lib.sh" ; then
+	echo "Failed to load the main script library"
+	exit 99
+fi
 
-err() {
-	say "${@}" 1>&2
-}
-
-fail() {
-	err "ERROR: ${@}"
-	exit 1
-}
-
-usage() {
-	err "usage: ${SCRIPT} [-o] [-s [-]status1,status2,...,statusN] [-t [-]type1,type2,...,typeN]"
-	for e in "${@}" ; do
-		err "\t${e}"
-	done
-	exit 1
-}
+USAGE_DETAILS="[-o] [-s [-]status1,status2,...,statusN] [-t [-]type1,type2,...,typeN]"
 
 SORTED="false"
 STATUS_SET="false"
diff --git a/cli/caliente/scripts/get_predicate b/cli/caliente/scripts/get_predicate
--- a/cli/caliente/scripts/get_predicate
+++ b/cli/caliente/scripts/get_predicate
@@ -3,18 +3,10 @@ SCRIPT="$(readlink -f "${0}")"
 BASEDIR="$(dirname "${0}")"
 SCRIPT="$(basename "${0}")"
 
-say() {
-	echo -e "${@}"
-}
-
-err() {
-	say "${@}" 1>&2
-}
-
-fail() {
-	err "ERROR: ${@}"
-	exit 1
-}
+if ! . "${BASEDIR}/caliente.lib.sh" ; then
+	echo "Failed to load the main script library"
+	exit 99
+fi
 
 for log in "${@}" ; do
 	egrep "^[[:space:]]export.predicate[[:space:]]=[[:space:]]\[.*\]$" "${log}"
diff --git a/cli/caliente/scripts/id2pred b/cli/caliente/scripts/id2pred
--- a/cli/caliente/scripts/id2pred
+++ b/cli/caliente/scripts/id2pred
@@ -3,26 +3,12 @@ SCRIPT="$(readlink -f "${0}")"
 BASEDIR="$(dirname "${0}")"
 SCRIPT="$(basename "${0}")"
 
-say() {
-	echo -e "${@}"
-}
+if ! . "${BASEDIR}/caliente.lib.sh" ; then
+	echo "Failed to load the main script library"
+	exit 99
+fi
 
-err() {
-	say "${@}" 1>&2
-}
-
-fail() {
-	err "ERROR: ${@}"
-	exit 1
-}
-
-usage() {
-    err "usage: ${SCRIPT} basetype"
-    for e in "${@}" ; do
-        err "\t${e}"
-    done
-    exit 2
-}
+USAGE_DETAILS="basetype"
 
 [ ${#} -ne 1 ] && usage "Must provide the base type to generate the prediate with"
 BASETYPE="${1}"
diff --git a/cli/caliente/scripts/summarize_manifest b/cli/caliente/scripts/summarize_manifest
--- a/cli/caliente/scripts/summarize_manifest
+++ b/cli/caliente/scripts/summarize_manifest
@@ -3,18 +3,10 @@ SCRIPT="$(readlink -f "${0}")"
 BASEDIR="$(dirname "${0}")"
 SCRIPT="$(basename "${0}")"
 
-say() {
-	echo -e "${@}"
-}
-
-err() {
-	say "${@}" 1>&2
-}
-
-fail() {
-	err "ERROR: ${@}"
-	exit 1
-}
+if ! . "${BASEDIR}/caliente.lib.sh" ; then
+	echo "Failed to load the main script library"
+	exit 99
+fi
 
 do_list() {
 	local manifest="${1}"
@@ -23,16 +15,13 @@ do_list() {
 	"${CSVTOOL}" -u ' ' col 3,5,7 "${manifest}" | grep -v "^TYPE "
 }
 
-CSVTOOL="$(which csvtool)"
-[ -z "${CSVTOOL}" ] && CSVTOOL="/usr/bin/csvtool"
-[ -f "${CSVTOOL}" ] || fail "csvtool is not installed, this tool is required by this script"
-[ -x "${CSVTOOL}" ] || fail "csvtool is not executable, this tool is required by this script"
-
 if [ ${#} -lt 1 ] ; then
 	err "usage: ${SCRIPT} manifest1 [manifest2 manifest3 ... manifestN]"
 	exit 1
 fi
 
+CSVTOOL=""
 for n in "${@}" ; do
+	[ -z "${CSVTOOL}" ] && CSVTOOL="$(find_exe csvtool true)"
 	do_list "${n}"
 done
